version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db-dev
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-dev:
    image: postgres:17
    environment:
      POSTGRES_DB: daylog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./.db/dev/:/var/lib/postgresql/data
  