version: "3.8"

services:
  app:
    image: devyusupov/daylog:latest
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python3 manage.py wait_for_db &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: daylog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./.db/:/var/lib/postgresql/data
      