# Generated by Django 5.2.4 on 2025-10-14 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='6-digit OTP code for password reset', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this OTP has been used for password reset')),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts made with this OTP')),
                ('user', models.ForeignKey(help_text='The user this password reset OTP belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'ordering': ['-created_at'],
            },
        ),
    ]
