# Generated by Django 5.2.4 on 2025-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_tag_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for sharing this entry via a link.', max_length=64, null=True, unique=True),
        ),
    ]
